### ISSUE TITLE
GDAL_DATA not set

### ISSUE THREAD

**Issue by jthiard** [Someware-fr/gdalmanylinux#2]
https://github.com/Someware-fr/gdalmanylinux/blob/068b204caffaecbe6dcd61285403e726ed8aa89c/gdalinit.py#L34-L37

This fail with GDAL >= 3.0 which does not seems to have `pcs.csv` files any more.

**Comment by jthiard** [comment]
@bgsomeware 
Looks like we also need to set

```python
os.environ['OSM_CONFIG_FILE'] =  os.path.join(os.environ['GDAL_DATA'], 'osmconf.ini')
```
for the OSM driver.

**Comment by bgsomeware** [comment]
This code reproduces the issue when OSM_CONFIG_FILE is not set :
`
driver = ogr.GetDriverByName('OSM')
ds = driver.Open('/vsicurl/http://download.openstreetmap.fr/extracts/europe/france/bretagne/ille_et_vilaine.osm.pbf')
`

**Comment by jthiard** [comment]
@bgsomeware I uploaded a new wheel from #4 could you please install it and check it is OK ?
Thanks.

**Comment by jthiard** [comment]
FYI, I added some tests related to this one in #5
